# Generated by Django 4.1.3 on 2022-12-15 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_profile_email_profile_username_alter_profile_disease'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='password',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
